"use client";

import { AuroraBackground } from "@/components/auth/aurora-background";
import { Radio, Signal, Headphones } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

import { useState, useEffect } from "react";

export default function LiveRadioPage() {
    const [mounted, setMounted] = useState(false);
    const [bars, setBars] = useState<{ height: number; duration: number; delay: number }[]>([]);

    useEffect(() => {
        // eslint-disable-next-line
        setMounted(true);
        setBars(Array.from({ length: 20 }).map((_, i) => ({
            height: Math.random() * 80 + 20,
            duration: Math.random() * 0.5 + 0.5,
            delay: i * 0.05
        })));
    }, []);
    return (
        <div className="min-h-screen bg-black text-white pt-32 pb-24 px-6 md:px-12 font-geist-sans selection:bg-ekko-500 selection:text-white">
            <div className="fixed inset-0 z-0 pointer-events-none">
                <AuroraBackground className="opacity-20" />
                <div className="absolute inset-0 bg-[url('/grid-pattern.svg')] opacity-10" />
            </div>

            <div className="relative z-10 max-w-6xl mx-auto flex flex-col items-center text-center">
                <div className="inline-flex items-center gap-2 border border-ekko-500/30 bg-ekko-500/10 px-3 py-1 text-ekko-300 text-[10px] uppercase tracking-widest mb-6 rounded-full animate-pulse">
                    <span className="w-2 h-2 rounded-full bg-ekko-500" />
                    Live Now
                </div>
                <h1 className="text-6xl md:text-9xl font-black tracking-tighter mb-8 text-white uppercase">
                    24/7 <span className="text-transparent bg-clip-text bg-gradient-to-r from-ekko-400 to-ekko-600">Global</span> <br /> Stream
                </h1>
                <p className="text-xl text-neutral-400 max-w-3xl mx-auto leading-relaxed mb-16">
                    Tune into an endless, non-stop broadcast generated by AI. Curated by the community, powered by the machine.
                </p>

                <div className="w-full max-w-4xl aspect-video bg-neutral-900 rounded-none border border-white/10 relative overflow-hidden group mb-12 shadow-2xl shadow-ekko-500/10">
                    <div className="absolute inset-0 flex items-center justify-center">
                        <div className="w-full h-full bg-[url('/hero-main.png')] bg-cover opacity-20" />
                    </div>

                    {/* Visualizer bars placeholder */}
                    <div className="absolute bottom-0 left-0 right-0 h-32 flex items-end justify-center px-8 pb-8 gap-2 opacity-50">
                        {mounted && bars.map((bar, i) => (
                            <div
                                key={i}
                                className="w-3 bg-ekko-500 rounded-t-full animate-bounce"
                                style={{
                                    height: `${bar.height}%`,
                                    animationDuration: `${bar.duration}s`,
                                    animationDelay: `${bar.delay}s`
                                }}
                            />
                        ))}
                    </div>

                    <div className="absolute inset-0 flex items-center justify-center">
                        <Button asChild className="h-16 w-16 rounded-full bg-white text-black hover:scale-110 transition-transform shadow-[0_0_30px_rgba(255,255,255,0.5)] flex items-center justify-center pl-1">
                            <Link href="/login">
                                <span className="sr-only">Play</span>
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M8 5V19L19 12L8 5Z" />
                                </svg>
                            </Link>
                        </Button>
                    </div>
                </div>

                <div className="grid md:grid-cols-3 gap-8 w-full max-w-5xl">
                    <div className="bg-neutral-900/50 backdrop-blur border border-white/5 p-6 rounded-none flex flex-col items-center">
                        <Radio className="w-8 h-8 text-neutral-400 mb-4" />
                        <h3 className="font-bold text-lg mb-2">Generic-Free</h3>
                        <p className="text-sm text-neutral-500">No repetitive playlists. Every hour is uniquely synthesized.</p>
                    </div>
                    <div className="bg-neutral-900/50 backdrop-blur border border-white/5 p-6 rounded-none flex flex-col items-center">
                        <Signal className="w-8 h-8 text-neutral-400 mb-4" />
                        <h3 className="font-bold text-lg mb-2">Low Bandwidth</h3>
                        <p className="text-sm text-neutral-500">Optimized Opus codec usage for crystal clear audio even on weak signals.</p>
                    </div>
                    <div className="bg-neutral-900/50 backdrop-blur border border-white/5 p-6 rounded-none flex flex-col items-center">
                        <Headphones className="w-8 h-8 text-neutral-400 mb-4" />
                        <h3 className="font-bold text-lg mb-2">Background Play</h3>
                        <p className="text-sm text-neutral-500">Keep the vibe going while you work, study, or commute.</p>
                    </div>
                </div>
            </div>
        </div>
    );
}
